import { Flight } from "@/types";

const destinations: Omit<Flight, "id">[] = [
  {
    destination: "Barcelona",
    destinationCode: "BCN",
    description:
      "Sun-drenched beaches, Gaudi's masterpieces, and tapas bars that never close. Barcelona is the Mediterranean at its most vibrant.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Barcelona El Prat",
      arrivalCode: "BCN",
      departureTime: "06:45 AM",
      landingTime: "10:15 AM",
      airline: "SAS",
    },
    returnFlight: {
      departureAirport: "Barcelona El Prat",
      departureCode: "BCN",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "03:20 PM",
      landingTime: "06:50 PM",
      airline: "SAS",
    },
    price: { basic: 2490, withLuggage: 3190, currency: "SEK" },
  },
  {
    destination: "Nice",
    destinationCode: "NCE",
    description:
      "The jewel of the French Riviera. Azure waters, pastel-colored old town, and the best salade nicoise you'll ever have.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Nice Cote d'Azur",
      arrivalCode: "NCE",
      departureTime: "07:30 AM",
      landingTime: "10:45 AM",
      airline: "Norwegian",
    },
    returnFlight: {
      departureAirport: "Nice Cote d'Azur",
      departureCode: "NCE",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "05:00 PM",
      landingTime: "08:15 PM",
      airline: "Norwegian",
    },
    price: { basic: 1890, withLuggage: 2590, currency: "SEK" },
  },
  {
    destination: "Rome",
    destinationCode: "FCO",
    description:
      "Ancient ruins, world-class pasta, and a city that wears its 2000-year history like a well-tailored suit.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Rome Fiumicino",
      arrivalCode: "FCO",
      departureTime: "08:00 AM",
      landingTime: "11:30 AM",
      airline: "Ryanair",
    },
    returnFlight: {
      departureAirport: "Rome Fiumicino",
      departureCode: "FCO",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "02:15 PM",
      landingTime: "05:45 PM",
      airline: "Ryanair",
    },
    price: { basic: 1590, withLuggage: 2290, currency: "SEK" },
  },
  {
    destination: "Athens",
    destinationCode: "ATH",
    description:
      "Where Western civilization began. The Acropolis at sunset, souvlaki on every corner, and island ferries waiting at Piraeus.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Athens Eleftherios",
      arrivalCode: "ATH",
      departureTime: "06:15 AM",
      landingTime: "11:00 AM",
      airline: "Aegean",
    },
    returnFlight: {
      departureAirport: "Athens Eleftherios",
      departureCode: "ATH",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "01:30 PM",
      landingTime: "04:15 PM",
      airline: "Aegean",
    },
    price: { basic: 2190, withLuggage: 2890, currency: "SEK" },
  },
  {
    destination: "Valletta",
    destinationCode: "MLA",
    description:
      "A fortress city floating in the Mediterranean. Honey-colored limestone, crystal-clear harbors, and centuries of Maltese history.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Malta International",
      arrivalCode: "MLA",
      departureTime: "09:00 AM",
      landingTime: "01:00 PM",
      airline: "Air Malta",
    },
    returnFlight: {
      departureAirport: "Malta International",
      departureCode: "MLA",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "04:30 PM",
      landingTime: "08:30 PM",
      airline: "Air Malta",
    },
    price: { basic: 2790, withLuggage: 3490, currency: "SEK" },
  },
  {
    destination: "Dubrovnik",
    destinationCode: "DBV",
    description:
      "The Pearl of the Adriatic. Walk the ancient city walls, kayak the crystal coast, and lose yourself in marble-paved streets.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Dubrovnik Airport",
      arrivalCode: "DBV",
      departureTime: "07:15 AM",
      landingTime: "10:30 AM",
      airline: "Croatia Airlines",
    },
    returnFlight: {
      departureAirport: "Dubrovnik Airport",
      departureCode: "DBV",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "11:45 AM",
      landingTime: "03:00 PM",
      airline: "Croatia Airlines",
    },
    price: { basic: 2390, withLuggage: 3090, currency: "SEK" },
  },
  {
    destination: "Split",
    destinationCode: "SPU",
    description:
      "A Roman emperor's palace turned living city. Dalmatian coast perfection with island-hopping at your doorstep.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Split Airport",
      arrivalCode: "SPU",
      departureTime: "06:30 AM",
      landingTime: "09:15 AM",
      airline: "Norwegian",
    },
    returnFlight: {
      departureAirport: "Split Airport",
      departureCode: "SPU",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "10:30 AM",
      landingTime: "01:15 PM",
      airline: "Norwegian",
    },
    price: { basic: 1990, withLuggage: 2690, currency: "SEK" },
  },
  {
    destination: "Palma de Mallorca",
    destinationCode: "PMI",
    description:
      "More than the party island. Think hidden coves, Serra de Tramuntana mountains, and some of the best cycling in Europe.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Palma de Mallorca",
      arrivalCode: "PMI",
      departureTime: "08:30 AM",
      landingTime: "12:00 PM",
      airline: "SAS",
    },
    returnFlight: {
      departureAirport: "Palma de Mallorca",
      departureCode: "PMI",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "01:30 PM",
      landingTime: "05:00 PM",
      airline: "SAS",
    },
    price: { basic: 1790, withLuggage: 2490, currency: "SEK" },
  },
  {
    destination: "Naples",
    destinationCode: "NAP",
    description:
      "Raw, chaotic, unforgettable. The birthplace of pizza, gateway to Pompeii and the Amalfi Coast.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Naples International",
      arrivalCode: "NAP",
      departureTime: "07:00 AM",
      landingTime: "10:45 AM",
      airline: "Ryanair",
    },
    returnFlight: {
      departureAirport: "Naples International",
      departureCode: "NAP",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "12:00 PM",
      landingTime: "03:45 PM",
      airline: "Ryanair",
    },
    price: { basic: 1490, withLuggage: 2190, currency: "SEK" },
  },
  {
    destination: "Marseille",
    destinationCode: "MRS",
    description:
      "France's oldest city and its most multicultural. Bouillabaisse by the port, calanques for days, and gritty Mediterranean charm.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Marseille Provence",
      arrivalCode: "MRS",
      departureTime: "09:15 AM",
      landingTime: "12:30 PM",
      airline: "Air France",
    },
    returnFlight: {
      departureAirport: "Marseille Provence",
      departureCode: "MRS",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "03:00 PM",
      landingTime: "06:15 PM",
      airline: "Air France",
    },
    price: { basic: 2090, withLuggage: 2790, currency: "SEK" },
  },
  {
    destination: "Venice",
    destinationCode: "VCE",
    description:
      "A city built on water and dreams. Gondolas, glass-blowing on Murano, and aperol spritz overlooking the Grand Canal.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Venice Marco Polo",
      arrivalCode: "VCE",
      departureTime: "06:00 AM",
      landingTime: "08:45 AM",
      airline: "SAS",
    },
    returnFlight: {
      departureAirport: "Venice Marco Polo",
      departureCode: "VCE",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "04:00 PM",
      landingTime: "06:45 PM",
      airline: "SAS",
    },
    price: { basic: 2290, withLuggage: 2990, currency: "SEK" },
  },
  {
    destination: "Santorini",
    destinationCode: "JTR",
    description:
      "White-washed clifftop villages, volcanic beaches, and sunsets that justify every Instagram cliche.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Santorini Airport",
      arrivalCode: "JTR",
      departureTime: "05:45 AM",
      landingTime: "11:15 AM",
      airline: "Aegean",
    },
    returnFlight: {
      departureAirport: "Santorini Airport",
      departureCode: "JTR",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "12:30 PM",
      landingTime: "04:00 PM",
      airline: "Aegean",
    },
    price: { basic: 3190, withLuggage: 3890, currency: "SEK" },
  },
  {
    destination: "Lisbon",
    destinationCode: "LIS",
    description:
      "Pastel de nata, fado music drifting through tiled alleyways, and tram 28 rattling through seven hills of pure character.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Lisbon Humberto Delgado",
      arrivalCode: "LIS",
      departureTime: "07:45 AM",
      landingTime: "11:30 AM",
      airline: "TAP Portugal",
    },
    returnFlight: {
      departureAirport: "Lisbon Humberto Delgado",
      departureCode: "LIS",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "02:00 PM",
      landingTime: "07:45 PM",
      airline: "TAP Portugal",
    },
    price: { basic: 2590, withLuggage: 3290, currency: "SEK" },
  },
  {
    destination: "Malaga",
    destinationCode: "AGP",
    description:
      "Picasso's birthplace on the Costa del Sol. Year-round sun, chiringuitos on the beach, and the Alhambra a train ride away.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Malaga Costa del Sol",
      arrivalCode: "AGP",
      departureTime: "08:15 AM",
      landingTime: "12:00 PM",
      airline: "Norwegian",
    },
    returnFlight: {
      departureAirport: "Malaga Costa del Sol",
      departureCode: "AGP",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "01:00 PM",
      landingTime: "04:45 PM",
      airline: "Norwegian",
    },
    price: { basic: 1690, withLuggage: 2390, currency: "SEK" },
  },
  {
    destination: "Sardinia",
    destinationCode: "OLB",
    description:
      "Italy's wild island. Emerald waters rivaling the Caribbean, rugged interior mountains, and pecorino with everything.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Olbia Costa Smeralda",
      arrivalCode: "OLB",
      departureTime: "06:30 AM",
      landingTime: "10:00 AM",
      airline: "Ryanair",
    },
    returnFlight: {
      departureAirport: "Olbia Costa Smeralda",
      departureCode: "OLB",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "11:00 AM",
      landingTime: "02:30 PM",
      airline: "Ryanair",
    },
    price: { basic: 1890, withLuggage: 2590, currency: "SEK" },
  },
  {
    destination: "Mykonos",
    destinationCode: "JMK",
    description:
      "Windmills, whitewash, and world-famous nightlife. But also quiet beaches, Little Venice, and the best gyros in the Cyclades.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Mykonos Airport",
      arrivalCode: "JMK",
      departureTime: "05:30 AM",
      landingTime: "10:45 AM",
      airline: "Aegean",
    },
    returnFlight: {
      departureAirport: "Mykonos Airport",
      departureCode: "JMK",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "11:30 AM",
      landingTime: "04:45 PM",
      airline: "Aegean",
    },
    price: { basic: 3490, withLuggage: 4190, currency: "SEK" },
  },
  {
    destination: "Hvar",
    destinationCode: "SPU",
    description:
      "Croatia's lavender island. Medieval town squares, secluded beaches, and wine from vines older than most countries.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Split Airport",
      arrivalCode: "SPU",
      departureTime: "07:00 AM",
      landingTime: "09:45 AM",
      airline: "Croatia Airlines",
    },
    returnFlight: {
      departureAirport: "Split Airport",
      departureCode: "SPU",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "05:15 PM",
      landingTime: "08:00 PM",
      airline: "Croatia Airlines",
    },
    price: { basic: 2290, withLuggage: 2990, currency: "SEK" },
  },
  {
    destination: "Kotor",
    destinationCode: "TGD",
    description:
      "A fjord in the Mediterranean. Walled old town at the foot of dramatic mountains, and Montenegro's best-kept secret.",
    outbound: {
      departureAirport: "Stockholm Arlanda",
      departureCode: "ARN",
      arrivalAirport: "Podgorica Airport",
      arrivalCode: "TGD",
      departureTime: "08:00 AM",
      landingTime: "11:30 AM",
      airline: "Montenegro Airlines",
    },
    returnFlight: {
      departureAirport: "Podgorica Airport",
      departureCode: "TGD",
      arrivalAirport: "Stockholm Arlanda",
      arrivalCode: "ARN",
      departureTime: "12:30 PM",
      landingTime: "04:00 PM",
      airline: "Montenegro Airlines",
    },
    price: { basic: 2690, withLuggage: 3390, currency: "SEK" },
  },
];

export function getMockFlights(): Flight[] {
  return destinations.map((d, i) => ({
    ...d,
    id: `mock-${i}-${d.destinationCode}`,
  }));
}

export function searchMockFlights(from: string): Flight[] {
  const all = getMockFlights();
  if (!from.trim()) return all;
  return all.map((f) => ({
    ...f,
    outbound: { ...f.outbound, departureAirport: from },
    returnFlight: { ...f.returnFlight, arrivalAirport: from },
  }));
}
